### PR TITLE
Added Webp Images and fallback system for faster loading speeds

### LINKED ISSUE #46: Add webp Images for fast load times with best quality compression
## Description
Webp is a standard by google specifically made for web and is supported by maxium platforms (other than apple safari for now) .. it has newer and better compression algorithm giving better results compared to normal .jpg or .jpeg or .png in smaller size

for more info https://developers.google.com/speed/webp/

for apple devices we can add a fallback system which changes loads normal file if error occurs

**Are you working on this**
Yes I am working on this issue :)

### PR DESCRIPTION
**Pull request by scixor**
## Changes Made
- fixes #46 
- added/converted manually over 150+ images to webp while keeping the older versions
- added fallback system which changes to native image if error is found

For referernce native files (those 150+ which were converted) were about 35mb and after conversion its only 5mb with almost all the quality retained

## What are the things you have done to make sure this feature works?

- I could have just made a powershell script to convert all the images to webp with certain compression ratio, but I went through all of them individually to ensure smaller sized images don't get too compressed (as they are already too small)...**FOR REFERENCE : the quality retained setting percentage is set between 60 percent to 85 percent depending on type of image**_(90+ is lossless format which increases the size of image instead.. used for more quality based image)_
- checked every changes to the `index.html` page and made sure fallback system is working

## Preview 
https://sid911.github.io/thai.opentechsummit.asia/

image

image

### CODE REVIEW

**Comment by Sid911** [comment]
@mariobehling Please review 😄 This was a lot of work

**Comment by scixor** [comment]
And lot of the changes can even be used more in different pages

**Comment by scixor** [comment]
@mariobehling @kushthedude @snitin315 Please review..

**Comment by mariobehling** [comment]
Such a change could result in incompatibilities across our pages. Also, this is an event that is already over for some time. The only thing we want is to document this event correctly. We don't have resources to review major changes apart from that. Mentors need to focus on main project instead of changing the image formatting reviews. Therefore closing this. Thanks.

**Pull request closed without merging**
