### PR TITLE
Added fossasia profiles links

### PR DESCRIPTION
**Pull request by prashant5878-shukla**
#38  added missing social links
Preview link:https://coder135792468.github.io/thai.opentechsummit.asia/
Added wekepedia

### CODE REVIEW

**Review by NishithP2004 — CHANGES_REQUESTED** [review]
Please remove Google +

**Comment by NishithP2004** [comment]
I believe that you have added only Wikipedia as a new link, if yes please specify in the PR description that you have added Wikipedia.

**Comment by NishithP2004** [comment]
This issue #38 is invalid in accordance to this PR.

**Comment by NishithP2004** [comment]
Please create a new issue.

**Comment by prashant5878-shukla** [comment]
@NishithP2004 please see it again

**Comment by prashant5878-shukla** [comment]
This is not an issue ?
Can I solve this ?

**Comment by mariobehling** [comment]
German WP links is not relevant for this website. Therefore closing this PR.

**Comment by prashant5878-shukla** [comment]
@mariobehling I added the links that are given in the task . What actually I have to do ?

**Pull request closed without merging**
